- command: "kubectl get secret {{item.secret}}"
  register: command_result
  ignore_errors: True

- template: 
    src: secret.yml
    dest: /tmp/secret.yml
  #when: 'item.secret not in command_result.stdout'

- command: "kubectl create -f /tmp/secret.yml"
  when: 'item.secret not in command_result.stdout'