apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - nexus.{{domaine}}
    secretName: certificate
  rules:
  - host: nexus.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-sonatype-nexus
          servicePort: 8080