apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - nexus.{{domaine}}
    secretName: certificate
  rules:
  - host: registry.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 8082