apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "50m"    
spec:
  tls:
  - hosts:
    - nexus.{{domaine}}
    secretName: certificate
  rules:
  - host: registry.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 8082
