
- template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - ingress.yml

- command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  ignore_errors: true
  with_items:
    - pv.yml
    - ingress.yml

- name: Install sonarqube
  command: ./helm install --name sonarqube stable/sonarqube
  args: 
    chdir: ~/linux-amd64
  ignore_errors: true
  become: yes

#- name: create rolebinding admin
#  command: kubectl create rolebinding sonarqube-admin-binding --clusterrole=admin --user=system:serviceaccount:default:default
#  become: yes
#  ignore_errors: true