domaine: k8.wildwidewest.xyz

registry: registry.{{domaine}}

acme: https://acme-v02.api.letsencrypt.org/directory
#acme: https://acme-staging-v02.api.letsencrypt.org/directory

nfs_server: 10.16.103.9

nfs_mounts:
  - { remote: "{{nfs_server}}:/zpool-126262/WWWJENKINS",   local: /mnt/jenkins}
  - { remote: "{{nfs_server}}:/zpool-126262/WWWNEXUS",     local: /mnt/nexus}
  - { remote: "{{nfs_server}}:/zpool-126262/WWWSONARQUBE", local: /mnt/sonarqube}
  - { remote: "{{nfs_server}}:/zpool-126262/WWWELASTICSEARCH",  local: /mnt/elasticsearch}
  - { remote: "{{nfs_server}}:/zpool-126262/K8SBACKUP",    local: /mnt/backup}
  - { remote: "{{nfs_server}}:/zpool-126262/K8SNFS",       local: /mnt/nfs_provisioner}

kubeadm:
  init:
    options: