domaine: k8.wildwidewest.xyz

registry: registry.{{domaine}}

acme: https://acme-v02.api.letsencrypt.org/directory
#acme: https://acme-staging-v02.api.letsencrypt.org/directory

nfs_mounts:
  - { remote: "10.16.103.9:/zpool-126262/WWWJENKINS",   local: /mnt/jenkins}
  - { remote: "10.16.103.9:/zpool-126262/WWWGRAV",   local: /mnt/grav}
  - { remote: "10.16.103.9:/zpool-126262/WWWNEXUS",     local: /mnt/nexus}
  - { remote: "10.16.103.9:/zpool-126262/WWWKEYCLOAK",  local: /mnt/keycloak}
  - { remote: "10.16.103.9:/zpool-126262/WWWSONARQUBE", local: /mnt/sonarqube}

traefik:
  ssl: "{{ traefik_ssl | default(True) }}"

kubeadm:
  init:
    options:

certificates:
  - jenkins.{{domaine}}
  - nexus.{{domaine}}
  - sonarqube.{{domaine}}
  - keycloak.{{domaine}}
 # - kibana.{{domaine}}
  - meltingpoc.{{domaine}}
  - parcours-integration.{{domaine}}
  - recyclette.{{domaine}}
  - wallboard.{{domaine}}
  - wallboard-back.{{domaine}}
  - bus.wallboard.{{domaine}}
