domaine: k8.wildwidewest.xyz

registry: registry.{{domaine}}

nfs_mounts:
  - { remote: "10.16.103.9:/zpool-126262/WWWJENKINS",   local: /mnt/jenkins}
  - { remote: "10.16.103.9:/zpool-126262/WWWNEXUS",     local: /mnt/nexus}
  - { remote: "10.16.103.9:/zpool-126262/WWWKEYCLOAK",  local: /mnt/keycloak}
  - { remote: "10.16.103.9:/zpool-126262/WWWSONARQUBE", local: /mnt/sonarqube}
#  - { remote: 10.16.103.9:/zpool-126262/WWWJENKINS, locale: /mnt/logstash_0}

traefik:
  ssl: "{{ traefik_ssl | default(True) }}"

kubeadm:
  init:
    options:

certificates:
  - jenkins.{{domaine}}
  - nexus.{{domaine}}
  - sonarqube.{{domaine}}
  - keycloak.{{domaine}}
  - kibana.{{domaine}}
  - meltingpoc.{{domaine}}
  - recyclette.{{domaine}}
  - wallboard.{{domaine}}
  - wallboard-back.{{domaine}}
  - bus.wallboard.{{domaine}}
