
- name: Copy Resources 
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - ingress.yml

- name: Create Kubernetes Resources
  command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
    - pv.yml
    - ingress.yml

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Install sonarqube
  command: helm install --name sonarqube stable/sonarqube
  become: yes
  when: "'sonarqube' not in helm_list.stdout"