apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
  - hosts:
    - nexus.{{domaine}}
    secretName: certificate
  rules:
  - host: sonarqube.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube-sonarqube
          servicePort: 9000