---

- hosts: nfs-client
  roles:
    - { role: storage-client-nfs, tags: nfs }

- hosts: softwarefactory-docker
  roles:
    - { role: storage-client-nfs, tags: nfs }
    - { role: tool-logrotate, tags:  [logrotate, softwarefactory-docker ]}
    - { role: docker,         tags:  [docker, softwarefactory-docker ]}
    - { role: nginx,          tags:  [nginx, softwarefactory-docker ]}
    - { role: dck-jenkins,    tags:  [jenkins, softwarefactory-docker]}
    - { role: dck-nexus,      tags:  [nexus, softwarefactory-docker]}

- hosts: apps-front-docker
  roles:
    - { role: dck-app-front,      tags:  [dck-app-front, softwarefactory-docker]}

- hosts: apps-docker
  roles:
    - { role: docker,         tags:  [docker, softwarefactory-docker ]}
    - { role: nginx,          tags:  [nginx, softwarefactory-docker ]}
    - { role: dck-app,      tags:  [dck-app, softwarefactory-docker]}

- hosts: kubernetes
  roles:
    - { role: tool-logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: k8s, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
    - { role: k8s-master, tags:  [kubernetes-master, kubernetes]}

- hosts: kubernetes-slave
  roles:
    - { role: k8s-slave, tags: [kubernetes-slave, kubernetes] }

- hosts: helm
  roles:
    - { role: tool-helm, tags: tool-helm }

- hosts: cert-manager
  roles:
    - { role: cert-manager, tags: [ingress, cert-manager] }

- hosts: ingress
  roles:
    - { role: ingress-nginx, tags: [ingress, ingress-nginx] }

- hosts: softwarefactory
  roles:
    - { role: app-secrets, tags: [softwarefactory, secrets] }
    - { role: app-nexus, tags: [softwarefactory, nexus] }
    - { role: app-jenkins, tags: [softwarefactory, jenkins] }
    - { role: app-sonarqube, tags: [softwarefactory, sonarqube] }
    - { role: app-keycloak, tags: [softwarefactory, keycloak] }
#  - { role: app-grafana, tags: [softwarefactory, app-grafana] }

- hosts: middleware
  roles:
    - { role: app-kafka, tags: [middleware, kafka] }

- hosts: rook
  roles:
    - { role: storage-rook, tags: storage-rook }

- hosts: jenkins-x
  roles:
    - { role: app-jenkins-x, tags: [ jenkins-x ] }

- hosts: authorized-keys
  roles:
    - { role: config-authorized-keys, tags: authorized-keys }

- hosts: upgrade
  roles:
    - { role: util-upgrade, tags: upgrade }

- hosts: ping
  roles:
    - { role: util-ping, tags: ping }

- hosts: reboot
  roles:
    - { role: util-reboot, tags: reboot }
