---

- hosts: nfs-master
  roles:
    - { role: nfs-master, tags: nfs }

- hosts: nfs-client
  roles:
    - { role: nfs-client, tags: nfs }

- hosts: kubernetes
  roles:
    - { role: logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: kubernetes, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
    - { role: kubernetes-master, tags:  kubernetes}

- hosts: kubernetes-slave
  roles:
    - { role: kubernetes-slave, tags: kubernetes }

- hosts: helm
  roles:
    - { role: helm, tags: helm }

- hosts: traefik
  roles:
    - { role: cert-manager, tags: cert-manager }
    - { role: traefik, tags: traefik }

- hosts: kubernetes-tools
  roles:
    - { role: secrets, tags: secrets }
    - { role: nexus, tags: nexus }
    - { role: jenkins, tags: jenkins }
    - { role: sonarqube, tags: sonarqube }
    - { role: keycloak, tags: keycloak }
    - { role: kafka, tags: kafka }

- hosts: cert-manager
  roles:
    - { role: cert-manager, tags: cert-manager }
    - { role: traefik, tags: traefik }

- hosts: rook
  roles:
    - { role: rook, tags: rook }

- hosts: kibana
  roles:
    - { role: kibana, tags: kibana }

- hosts: reboot
  roles:
    - { role: reboot, tags: reboot }