---

- hosts: nfs-client
  roles:
  - { role: nfs-client, tags: nfs }

- hosts: kubernetes
  roles:
  - { role: logrotate, tags: kubernetes }
  - { role: docker, tags:  kubernetes}
  - { role: kubernetes, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
  - { role: kubernetes-master, tags:  [kubernetes-master, kubernetes]}

- hosts: kubernetes-slave
  roles:
  - { role: kubernetes-slave, tags: [kubernetes-slave, kubernetes] }

- hosts: helm
  roles:
  - { role: helm, tags: helm }

- hosts: ingress
  roles:
  - { role: cert-manager, tags: [ ingress, cert-manager] }
  - { role: ingress-nginx, tags: [ ingress-nginx, ingress] }

- hosts: softwarefactory
  roles:
  - { role: app-secrets, tags: [softwarefactory, app-secrets] }
  - { role: app-nexus, tags: [softwarefactory, app-nexus] }
  - { role: app-jenkins, tags: [softwarefactory, app-jenkins] }
  - { role: app-sonarqube, tags: [softwarefactory, app-sonarqube] }
  - { role: app-keycloak, tags: [softwarefactory, app-keycloak] }

- hosts: middleware
  roles:
  - { role: kafka, tags: [middleware, kafka] }

  #  - { role: kibana, tags: [softwarefactory, kibana] }

- hosts: rook
  roles:
  - { role: rook, tags: rook }

- hosts: upgrade
  roles:
  - { role: upgrade, tags: upgrade }

- hosts: ping
  roles:
  - { role: ping, tags: ping }

- hosts: reboot
  roles:
  - { role: reboot, tags: reboot }