---

- hosts: nfs-master
  roles:
    - { role: nfs-master, tags: nfs }

- hosts: nfs-client
  roles:
    - { role: nfs-client, tags: nfs }

- hosts: kubernetes-master
  roles:
    - { role: logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: kubernetes, tags:  kubernetes }
    - { role: kubernetes-master, tags:  kubernetes}

- hosts: kubernetes-slave
  roles:
    - { role: logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: kubernetes, tags:  kubernetes }
    - { role: kubernetes-slave, tags: kubernetes }

- hosts: kubernetes-tools
  roles:
    - { role: helm, tags: helm }
    #    - { role: usine, tags: usine }
#    - { role: nexus, tags: nexus }
    - { role: jenkins, tags: jenkins }
    - { role: traefik, tags: traefik }
#    - { role: keycloak, tags: keycloak }

   