---

- hosts: nfs-client
  roles:
    - { role: nfs-client, tags: nfs }

- hosts: kubernetes
  roles:
    - { role: logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: kubernetes, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
    - { role: kubernetes-master, tags:  kubernetes}

- hosts: kubernetes-slave
  roles:
    - { role: kubernetes-slave, tags: kubernetes }

- hosts: helm
  roles:
    - { role: helm, tags: helm }

- hosts: ingress
  roles:
    - { role: cert-manager, tags: cert-manager }
    - { role: ingress-nginx, tags: ingress }

- hosts: softwarefactory
  roles:
    - { role: secrets, tags: [softwarefactory, secrets] }
    - { role: nexus, tags: [softwarefactory, nexus] }
#    - { role: jenkins, tags: [softwarefactory, jenkins] }
#    - { role: sonarqube, tags: [softwarefactory, sonarqube] }
#    - { role: keycloak, tags: [softwarefactory, keycloak] }
#    - { role: kafka, tags: [softwarefactory, kafka] }
#    - { role: kibana, tags: [softwarefactory, kibana] }

- hosts: jenkins-x
  roles:
    - { role: jenkins-x, tags: jenkins-x }

- hosts: cert-manager
  roles:
    - { role: cert-manager, tags: cert-manager }
    - { role: ingress-nginx, tags: ingress }

- hosts: rook
  roles:
    - { role: rook, tags: rook }

- hosts: upgrade
  roles:
    - { role: upgrade, tags: upgrade }

- hosts: ping
  roles:
    - { role: ping, tags: ping }

- hosts: reboot
  roles:
    - { role: reboot, tags: reboot }
