---

- hosts: all
  roles:
    - { role: util-crond, tags: [alert, crond] }

- hosts: nfs-client
  roles:
    - { role: storage-client-nfs, tags: nfs }

- hosts: softwarefactory-docker
  roles:
    - { role: storage-client-nfs, tags: nfs }
    - { role: tool-logrotate, tags:  [logrotate, softwarefactory-docker ]}
    - { role: docker,         tags:  [docker, softwarefactory-docker ]}
    - { role: nginx,          tags:  [nginx, softwarefactory-docker ]}
    - { role: dck-jenkins,    tags:  [jenkins, softwarefactory-docker]}
    - { role: dck-nexus,      tags:  [nexus, softwarefactory-docker]}

- hosts: apps-front-docker
  roles:
    - { role: dck-app-front,      tags:  [dck-app-front, softwarefactory-docker]}

- hosts: apps-docker
  roles:
    - { role: docker,         tags:  [docker, softwarefactory-docker ]}
    - { role: nginx,          tags:  [nginx, softwarefactory-docker ]}
    - { role: dck-app,      tags:  [dck-app, softwarefactory-docker]}

- hosts: kubernetes
  roles:
    - { role: tool-logrotate, tags: [log, kubernetes ] }
    - { role: network, tags: [network, kubernetes] }
    - { role: docker, tags:  [docker, kubernetes]}
    - { role: k8s, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
    - { role: k8s-master, tags:  [kubernetes-master]}

- hosts: kubernetes-slave
  roles:
    - { role: k8s-slave, tags: [kubernetes-slave] }

- hosts: helm
  roles:
    - { role: tool-helm, tags: tool-helm }

- hosts: cert-manager
  roles:
    - { role: k8s-namespace,    tags: [cert-manager, k8s-namespace] }
    - { role: app-secrets,      tags: [cert-manager, app-secrets] }
    - { role: k8s-cert-manager, tags: [cert-manager, k8s-cert-manager] }

- hosts: ingress
  roles:
    - { role: ingress-nginx,    tags: [ingress, ingress-nginx] }

- hosts: monitoring
  roles:
    - { role: k8s-dashboard, tags: [monitoring, k8s-dashboard] }

- hosts: softwarefactory
  roles:
    - { role: app-nexus, tags: [softwarefactory, nexus] }
    - { role: app-jenkins, tags: [softwarefactory, jenkins] }
    - { role: app-sonarqube, tags: [softwarefactory, sonarqube] }
#    - { role: app-keycloak, tags: [softwarefactory, keycloak] }

- hosts: rook
  roles:
    - { role: storage-rook, tags: storage-rook }

- hosts: authorized-keys
  roles:
    - { role: config-authorized-keys, tags: authorized-keys }

- hosts: upgrade
  roles:
    - { role: util-upgrade, tags: upgrade }

- hosts: ping
  roles:
    - { role: util-ping, tags: ping }

- hosts: reboot
  roles:
    - { role: util-reboot, tags: reboot }
