---
 
- hosts: kubernetes
  roles:
    - { role: logrotate, tags: kubernetes }
    - { role: docker, tags:  kubernetes}
    - { role: kubernetes, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
    - { role: kubernetes-master, tags:  kubernetes}
  
- hosts: kubernetes-slave
  roles:
    - { role: kubernetes-slave, tags: kubernetes }

- hosts: nfs-master
  roles:
    - { role: nfs-master, tags: nfs-master }

- hosts: nfs
  roles:
    - { role: nfs, tags: nfs }

- hosts: kubernetes-tools
  roles:
#    - { role: usine, tags: usine }
#    - { role: nexus, tags: nexus }
#    - { role: traefik, tags: traefik }
#    - { role: keycloak, tags: keycloak }
    - { role: helm, tags: helm }
   