---

- hosts: nfs-client
  roles:
  - { role: storage-client-nfs, tags: nfs }

- hosts: kubernetes
  roles:
  - { role: tool-logrotate, tags: kubernetes }
  - { role: docker, tags:  kubernetes}
  - { role: kubernetes, tags:  kubernetes }

- hosts: kubernetes-master
  roles:
  - { role: kubernetes-master, tags:  [kubernetes-master, kubernetes]}

- hosts: kubernetes-slave
  roles:
  - { role: kubernetes-slave, tags: [kubernetes-slave, kubernetes] }

- hosts: helm
  roles:
  - { role: tool-helm, tags: tool-helm }

- hosts: cert-manager
  roles:
  - { role: cert-manager, tags: [ ingress, cert-manager] }

- hosts: ingress
  roles:
  - { role: ingress-nginx, tags: [ ingress-nginx, ingress] }

- hosts: softwarefactory
  roles:
  - { role: app-secrets, tags: [softwarefactory, app-secrets] }
  - { role: app-nexus, tags: [softwarefactory, app-nexus] }
  - { role: app-jenkins, tags: [softwarefactory, app-jenkins] }
  - { role: app-sonarqube, tags: [softwarefactory, app-sonarqube] }
  - { role: app-keycloak, tags: [softwarefactory, app-keycloak] }

- hosts: middleware
  roles:
  - { role: middleware-kafka, tags: [middleware, middleware-kafka] }

  #  - { role: kibana, tags: [softwarefactory, kibana] }

- hosts: rook
  roles:
  - { role: storage-rook, tags: storage-rook }

- hosts: authorized-keys
  roles:
  - { role: config-authorized-keys, tags: authorized-keys }

- hosts: upgrade
  roles:
  - { role: util-upgrade, tags: upgrade }

- hosts: ping
  roles:
  - { role: util-ping, tags: ping }

- hosts: reboot
  roles:
  - { role: util-reboot, tags: reboot }
