- file:
    path: /nfs/keycloak-dev
    state: directory
    mode: 0755


- file:
    path: /nfs/jenkins-dev
    state: directory
    mode: 0755


- file:
    path: /nfs/nexus-dev
    state: directory
    mode: 0755

- lineinfile:
    path: /etc/fstab
    regexp: '^149.202.62.219:/var/nfs/keycloak-dev/'
    line: '149.202.62.219:/var/nfs/keycloak-dev/ /nfs/keycloak-dev/ nfs rw 0 0'

- lineinfile:
    path: /etc/fstab
    regexp: '^149.202.62.219:/var/nfs/jenkins-dev/'
    line: '149.202.62.219:/var/nfs/jenkins-dev/ /nfs/jenkins-dev/ nfs rw 0 0'

- lineinfile:
    path: /etc/fstab
    regexp: '^149.202.62.219:/var/nfs/nexus-dev/'
    line: '149.202.62.219:/var/nfs/nexus-dev/ /nfs/nexus-dev/ nfs rw 0 0'
