- name: Create /mnt/backup/pki/ folder
  file:
    path: /mnt/backup/pki/
    state: directory
  become: yes
  become_user: root

- name: Backup folder /etc/kubernetes/pki
  synchronize:
    src: /etc/kubernetes/pki
    dest: /mnt/backup/
  delegate_to: "{{ inventory_hostname }}"
  become: yes
  become_user: root

- name: Copy backup config
  template:
    src: backup.j2
    dest:  /tmp/k8s-backup.yaml
  become: yes
  become_user: root

- name: Create Backup
  k8s:
    state: present
    src: /tmp/k8s-backup.yaml
  become: yes
  become_user: root
