- name: Mandatory Command
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
  become: yes
  become_user: root

- name: Copy Resources
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
  - service.j2
  - patch.yml

- name: Create Service
  k8s:
    state: present
    src: /tmp/service.j2
  become: yes
  become_user: root

- set_fact:
    patch:
      data:
        "proxy-body-size": "100m"
        "proxy-buffering": "on"

- name: Patch ConfigMap
  shell: kubectl patch configmap nginx-configuration -n ingress-nginx --patch "$(cat /tmp/patch.yml)"
  ignore_errors: True
  become: yes

#- name: Install nginx-ingress
#  command: helm install stable/nginx-ingress --name nginx-ingress --set rbac.create=true
#  become: yes
#  when: "'nginx-ingress' not in helm_list.stdout"