- name: Copy .bashrc
  template:
    src: bashrc.j2
    dest: /root/.bashrc
  become: yes
  become_user: root

- name: Copy .profile
  template:
    src: bashrc.j2
    dest: /root/.profile
  become: yes
  become_user: root
