---

#heapster                        ClusterIP   10.106.99.131    <none>        8082/TCP    4m        app=jenkins-x-heapster
#jenkins                         ClusterIP   10.96.95.149     <none>        8080/TCP    4m        component=jenkins-x-jenkins-master
#jenkins-agent                   ClusterIP   10.103.237.106   <none>        50000/TCP   4m        component=jenkins-x-jenkins-master
#jenkins-x-chartmuseum           ClusterIP   10.98.12.155     <none>        8080/TCP    4m        app=chartmuseum,release=jenkins-x
#jenkins-x-docker-registry       ClusterIP   10.110.202.122   <none>        5000/TCP    4m        app=docker-registry,release=jenkins-x
#jenkins-x-mongodb               ClusterIP   10.98.102.146    <none>        27017/TCP   4m        app=jenkins-x-mongodb
#jenkins-x-monocular-api         ClusterIP   10.96.118.84     <none>        80/TCP      4m        app=jenkins-x-monocular-api
#jenkins-x-monocular-prerender   ClusterIP   10.111.68.83     <none>        80/TCP      4m        app=jenkins-x-monocular-prerender
#jenkins-x-monocular-ui          ClusterIP   10.97.48.134     <none>        80/TCP      4m        app=jenkins-x-monocular-ui
#nexus                           ClusterIP   10.99.41.34      <none>        80/TCP      4m        app=nexus,release=jenkins-x
          
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: nexus.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monocular-ui
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: monocular-ui.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-x-monocular-ui
          servicePort: 80


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: docker-registry.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-x-docker-registry
          servicePort: 5000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chartmuseum
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: chartmuseum.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-x-chartmuseum
          servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: jenkins.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heapster
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - secretName: certificate
  rules:
  - host: heapster.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: heapster
          servicePort: 8082
