apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: jx
    name: jenkins
  nfs:
    path: /zpool-126262/WWWJENKINSX
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-chartmuseum
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: jx
    name: jenkins-x-chartmuseum
  nfs:
    path: /zpool-126262/WWWJENKINSXCHARTMSM
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-docker-registry
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: jx
    name: jenkins-x-docker-registry
  nfs:
    path: /zpool-126262/WWWJENKINSXDOCKERREG
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-mongodb
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: jx
    name: jenkins-x-mongodb
  nfs:
    path: /zpool-126262/WWWJENKINSXMONGODB
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-nexus
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: jx
    name: jenkins-x-nexus
  nfs:
    path: /zpool-126262/WWWJENKINSXNEXUS/app
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle
