- name: Execute kubeadm reset
  command: kubeadm reset -f
  become: yes
  become_user: root

- name: Execute kubeadm init
  command: kubeadm init {{kubeadm.init.options | default('')}}
  register: kubeadm_init_message
  become: yes
  become_user: root

- name: "Create join master fact"
  set_fact:
     join_master: "{{kubeadm_init_message.stdout_lines[-1]}}"
  become: yes
  become_user: root

- name: Delete .kube folder
  file:
    path: ~/.kube
    state: absent
  become: yes
  become_user: root

- name: Create .kube folder
  file:
    path: ~/.kube
    state: directory
  become: yes
  become_user: root

- name: Copy admin.conf
  command: cp -i /etc/kubernetes/admin.conf ~/.kube/config
  become: yes
  become_user: root

- name: Get K8s version
  shell: kubectl version | base64 | tr -d '\n'
  register: k8_version
  become: yes
  become_user: root

#- name: Create K8s network
#  command: kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kube-router-all-service-daemonset.yaml
#  become: yes
#  become_user: root

- name: Create K8s network
  command: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{k8_version.stdout_lines[0]}}
  become: yes
  become_user: root