- name: Create kubernetes repo
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  become: yes
  become_user: root

- name: Disable selinux
  selinux:
    state: disabled
  become: yes
  become_user: root

- name: Ensure a list of packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
  vars:
    packages:
    - kubelet
    - kubeadm
    - ipvsadm
  become: yes
  become_user: root

- name: Start kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root

- name: Execute kubeadm reset
  command: kubeadm reset -f
  become: yes
  become_user: root