- name: "Ensure Packages are installed"
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
  vars:
    packages:
      - python-pip
      - rsync
      - ipvsadm
      - yum-utils
      - nc
  become: yes
  become_user: root

- name: "Install pip packages"
  pip:
    name:
      - pip==9.0.3
      - setuptools==40.6.3
      - openshift
  become: yes
  become_user: root