apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: keycloak-home
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      - name: keycloak
        image: jboss/keycloak
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_ADDR
          value: 127.0.0.1
        - name: DB_VENDOR
          value: POSTGRES
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_HOSTNAME
          value: keycloak.k8.wildwidewest.xyz
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: 127.0.0.1
      volumes:
      - name: keycloak-home
        persistentVolumeClaim:
          claimName: pvc-keycloak