apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: traefik-cert
  rules:
  - host: keycloak.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: 8080
