- command: helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
  become: yes
  become_user: root

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: "Status file /root/helm-elasticsearch"
  stat:
    path:  "/root/helm-elasticsearch"
  register: helm_elasticsearch_status
  become: yes
  become_user: root

- name: Clone elasticsearch chart
  command: git clone https://github.com/clockworksoul/helm-elasticsearch.git
  args:
    chdir: /root
  become: yes
  become_user: root
  when: helm_elasticsearch_status.stat.exists == False

- name: Install elasticsearch chart
  command: helm install --name elasticsearch helm-elasticsearch
  args:
    chdir: /root
  become: yes
  become_user: root
  when: "'elasticsearch' not in helm_list.stdout"

- name: Copy configs
  template:
    src: templates/{{item}}.yml
    dest: /tmp/{{item}}.yml
  with_items:
  - ingress
  - pv_data_logstash_0
  #  - filebeat-ds
  #  - logstash-config
  #  - logstash-deployment
  #  - logstash-service
  become: yes
  become_user: root

- name: Deploy configs
  command: kubectl apply -f /tmp/{{item}}.yml
  with_items:
  - ingress
  - pv_data_logstash_0
  #  - filebeat-ds
  #  - logstash-config
  #  - logstash-deployment
  #  - logstash-service
  become: yes
  become_user: root
