apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/jenkins_x
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-chartmuseum
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/jenkins_x_chartmuseum
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-docker-registry
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/jenkins_x_docker_registry
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-mongodb
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/jenkins_x_mongodb
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-x-nexus
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/jenkins_x_nexus
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle