apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: registry.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 8082
