apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nexus
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/nexus
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle