apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31922
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: nexus
    release: nexus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}