- name: Create dev k8s namespace
  k8s:
    name: dev
    api_version: v1
    kind: Namespace
    state: present

- name: Create prod k8s namespace
  k8s:
    name: prod
    api_version: v1
    kind: Namespace
    state: present