# REMOVE k8s_raw
- name: Create dev k8s namespace
  k8s_raw:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  become: yes
  become_user: root
  with_items: "{{ namespaces }}"