
- name: Mandatory Command
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
  become: yes
  become_user: root

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Copy Resources 
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - service.j2

- name: Create Resources
  command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
    - service.j2

#- name: Install nginx-ingress
#  command: helm install stable/nginx-ingress --name nginx-ingress --set rbac.create=true
#  become: yes
#  when: "'nginx-ingress' not in helm_list.stdout"