
- template: 
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - ingress.yml
    - ingress-registry.yml

- command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
    - pv.yml
    - ingress.yml
    - ingress-registry.yml

- name: Helm List
  command: helm list
  args:
    chdir: /root/linux-amd64
  become: yes
  become_user: root
  register: helm_list

- name: Install nexus
  command: helm install --name nexus stable/sonatype-nexus
  args: 
    chdir: ~/linux-amd64
  become: yes
  when: "'nexus' not in helm_list.stdout"

- command: kubectl expose deployment nexus-sonatype-nexus --name=registry --port=8082 --type=LoadBalancer
  become: yes
  become_user: root