
- template: 
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - service-registry.yml
    - ingress.yml
    - ingress-registry.yml

- command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  ignore_errors: true
  with_items:
    - pv.yml
    - service-registry.yml
    - ingress.yml
    - ingress-registry.yml
    
- name: Install nexus
  command: ./helm install --name nexus stable/sonatype-nexus
  args: 
    chdir: ~/linux-amd64
  ignore_errors: true
  become: yes