apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: jenkins.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
