- name: "Status file /root/helm-v2.12.1-linux-amd64.tar.gz"
  stat:
    path:  "/root/helm-v2.12.1-linux-amd64.tar.gz"
  register: helm_status
  become: yes
  become_user: root

- name: Download helm
  get_url:
    url: https://storage.googleapis.com/kubernetes-helm/helm-v2.12.1-linux-amd64.tar.gz
    dest: /root
  become: yes
  become_user: root
  when: helm_status.stat.exists == False

- name: Extract helm-v2.12.1-linux-amd64.tar.gz into /root
  unarchive:
    src: /root/helm-v2.12.1-linux-amd64.tar.gz
    dest: /root
    remote_src: True
  become: yes
  become_user: root

- name: List clusterrolebinding
  command: kubectl get clusterrolebinding
  become: yes
  become_user: root
  register: clusterrolebinding_check

- name: Create Role Binding
  command: kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
  become: yes
  become_user: root
  when: "'add-on-cluster-admin' not in clusterrolebinding_check.stdout"

- name: Create Role Binding
  command: kubectl create clusterrolebinding add-on-cluster-helm --clusterrole=cluster-admin --serviceaccount=default:default
  become: yes
  become_user: root
  when: "'add-on-cluster-helm' not in clusterrolebinding_check.stdout"

- name: Execute helm reset
  command: helm reset
  become: yes
  become_user: root
  ignore_errors: True
  
- name: Execute helm init
  command: helm init
  become: yes
  become_user: root