- name: Create Jenkins User
  user:
    name: jenkins
    group: docker
  become: true

- name: Copy Jenkins Docker Service File
  template:
    src: service.j2
    dest: /etc/systemd/system/jenkins.service
  become: true

- name: Copy Jenkins NGinx Conf File
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/jenkins.conf
  become: true

- name: Start Jenkins Service
  systemd:
    name: jenkins
    state: started
    enabled: yes
  become: yes
  become_user: root