- name: Copy PV
  template: src=templates/pv.yaml dest=/tmp/pv.yaml

- name: Copy PVC
  template: src=templates/pvc.yaml dest=/tmp/pvc.yaml

- name: Copy deployment
  template: src=templates/deployment.yaml dest=/tmp/deployment.yaml

- name: Copy Service
  template: src=templates/service.yaml dest=/tmp/service.yaml

- name: Copy Ingress
  template: src=templates/ingress.yaml dest=/tmp/ingress.yaml

- name: Deploy PV
  command: kubectl apply -f /tmp/pv.yaml -n usine

- name: Deploy PVC
  command: kubectl apply -f /tmp/pvc.yaml -n usine

- name: Deploy deployment
  command: kubectl apply -f /tmp/deployment.yaml -n usine

- name: Deploy Service
  command: kubectl apply -f /tmp/service.yaml -n usine

- name: Deploy Ingress
  command: kubectl apply -f /tmp/ingress.yaml -n usine