
- name: Copy Resources 
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - ingress.yml

- name: Create Resources
  command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
    - pv.yml
    - ingress.yml

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Install Jenkins
  command: helm install --name jenkins stable/jenkins
  become: yes
  when: "'jenkins' not in helm_list.stdout"

- name: Check
  command: kubectl get rolebinding
  become: yes
  become_user: root
  register: rolebinding_check

- name: create rolebinding admin
  command: kubectl create rolebinding jenkins-admin-binding --clusterrole=admin --user=system:serviceaccount:default:default
  become: yes
  when: "'jenkins-admin-binding' not in rolebinding_check.stdout"