- name: Install gcc
  yum:
    name: gcc
    state: present

- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name: Install python-devel
  yum:
    name: python-devel
    state: present