- name: Create Nexus User
  user:
    name: nexus
    group: docker
  become: true

- name: Copy Nexus Docker Service File
  template:
    src: service.j2
    dest: /etc/systemd/system/nexus.service
  become: true

- name: Copy Nexus NGinx Conf File
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/jenkins.conf
  become: true

- name: Start Nexus Service
  systemd:
    name: nexus
    state: started
    enabled: yes
  become: yes
  become_user: root