- name: Create Nexus User
  user:
    name: nexus
    group: docker
  become: true

- name: Copy Nexus Docker Service File
  template:
    src: service.j2
    dest: /etc/systemd/system/nexus.service
  become: true

- name: Copy Nexus NGinx Conf File
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/nexus.conf
  become: true

- name: Copy Nexus NGinx Conf File
  template:
    src: nginx-registry.j2
    dest: /etc/nginx/conf.d/registry.conf
  become: true

- name: Daemon Reload Nexus
  systemd:
    state: restarted
    daemon_reload: yes
    name: nexus

- name: Start Nexus Service
  systemd:
    name: nexus
    state: started
    enabled: yes
  become: yes
  become_user: root

- name: Create folder /etc/nexus
  file:
    path: /mnt/nexus
    state: directory
    mode: 0755
  become: yes
  become_user: root

#- name: Mount /mnt/nexus
#  command: mount /mnt/nexus