
- name: Copy Resources
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - pv.yml
    - ingress.yml

- name: Create Resources 
  command: "kubectl apply -f /tmp/{{item}} -n jx"
  become: yes
  with_items:
    - pv.yml
    - ingress.yml
