- name: Copy Resources
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
  - pv.yml
  - ingress.yml
  - ingress-registry.yml
  - patch.yml

- name: Create Resources
  command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
  - pv.yml
  - ingress.yml
  - ingress-registry.yml

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Install nexus
  command: helm install --name nexus stable/sonatype-nexus
  become: yes
  when: "'nexus' not in helm_list.stdout"

  #- name: "Patch Svc"
  #  command: kubectl patch svc nexus-sonatype-nexus --patch "$(cat /tmp/patch.yml)"

- name: Svc List
  command: kubectl get svc
  become: yes
  become_user: root
  register: svc_list

- command: kubectl expose deployment nexus-sonatype-nexus --name=registry --port=8082 --type=LoadBalancer
  become: yes
  become_user: root
  when: "'registry' not in svc_list.stdout"