apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
    - secretName: traefik-cert
  rules:
  - host: kibana.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch-elasticsearch-kibana
          servicePort: 80
