apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
    - secretName: traefik-cert
  rules:
  - host: keycloak.k8.wildwidewest.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: 8080
