apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs/sonarqube
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle