- name: "Copy Issuer"
  template:
    src: issuer.yaml
    dest: /tmp/issuer.yaml
  become: yes
  become_user: root

- name: Create Issuer
  k8s_raw:
    state: present
    src: "/tmp/issuer.yaml"
    namespace: "{{ namespace_item }}"
  become: yes
  become_user: root