- name: Copy Issuer
  template:
    src: issuer.yaml
    dest:  /tmp/issuer.yaml

- name: Create Issuer
  k8s:
    state: present
    src: /tmp/issuer.yaml
    namespace: "{{ namespace_item }}"
  become: yes
  become_user: root