- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Install cert-manager
  command: helm install --name cert-manager --namespace kube-system stable/cert-manager
  become: yes
  when: "'cert-manager' not in helm_list.stdout"

- name: Create Certificates
  include_tasks: create-certificate.yml
  loop_control:
    loop_var: namespace_item
  with_items: "{{namespaces}}"
