- name: kubeadm reset
  command: kubeadm reset

- name: kubeadm init
  command: kubeadm init
  register: kubeadm_init_message

- name: "Jojn master"
  set_fact:
     join_master: "{{kubeadm_init_message.stdout_lines[-1]}}"

- name: delete .kube folder
  file:
    path: ~/.kube
    state: absent

- name: create .kube folder
  file:
    path: ~/.kube
    state: directory

- name: copy admin.conf
  command: cp -i /etc/kubernetes/admin.conf ~/.kube/config

- name: Get K8s version
  shell: kubectl version | base64 | tr -d '\n'
  register: k8_version

- name: "Create k8s network"
  command: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{k8_version.stdout_lines[0]}}