- name: Create folder /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Configure Daemon.json
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker Service
  systemd:
    name: docker
    state: started
    enabled: yes