- name: Create folder /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  become: yes
  become_user: root

- name: "Create Folder docker.service.d"
  file:
    path: /etc/systemd/system/docker.service.d
    mode: 0755
    state: directory
  become: yes
  become_user: root

- name: Ensure a list of packages installed
  yum:
    name: yum-utils
    state: present
    update_cache: True
    validate_certs: false

- shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes
  become_user: root

- name: Ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
  vars:
    packages:
    - docker-ce
    - device-mapper-persistent-data
    - lvm2
  become: yes
  become_user: root

- name: Create Groupe Docker
  group:
    name: docker
    state: present
  become: yes
  become_user: root

- name: Configure Daemon.json
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  become: yes
  become_user: root
  when: registry is defined

- name: Configure Docker Service
  template:
    src: templates/etc_sysconfig_docker
    dest: /etc/sysconfig/docker
  become: yes
  become_user: root
  when: registry is defined

- name: Start Docker Service
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root