apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    namespace: default
    name: pvc-keycloak
  nfs:
    path: /zpool-126262/WWWKEYCLOAK
    server: "{{groups['nfs-master'][0] }}"
  persistentVolumeReclaimPolicy: Recycle
