---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      volumes:
{% if traefik.ssl is defined and traefik.ssl  == True %}
      - name: ssl
        secret:
          secretName: traefik-cert{% endif %}
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik:1.4-alpine
        name: traefik-ingress-lb
        volumeMounts:
{% if traefik.ssl is defined and traefik.ssl  == True %}
        - mountPath: "/ssl"
          name: "ssl"{% endif %}
        - mountPath: "/config"
          name: "config"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
{% if traefik.ssl is defined and traefik.ssl  == True %}
        - name: https
          containerPort: 443
          hostPort: 443{% endif %}
        - name: admin
          containerPort: 8081
        securityContext:
          privileged: true
        args:
        - -d
        - --web
        - --web.address=:8081
        - --kubernetes
        - --configfile=/config/traefik.toml
