- name: Helm List
  command: ./helm list
  args:
    chdir: /root/linux-amd64
  become: yes
  become_user: root
  register: helm_list

- name: Install cert-manager
  command: ./helm install --name cert-manager --namespace kube-system stable/cert-manager
  args: 
    chdir: ~/linux-amd64
  become: yes
  when: "'cert-manager' not in helm_list.stdout"

- name: Copy Issuer
  template:
    src: issuer.yaml
    dest:  /tmp/issuer.yaml

- name: Check
  command: kubectl get issuer -n kube-system
  become: yes
  become_user: root
  register: issuer_check

- name: Delete Issuer
  command: kubectl delete issuer letsencrypt-prod -n kube-system
  ignore_errors: True
  become: yes
  become_user: root
  when: "'letsencrypt-prod' in issuer_check.stdout"

- name: Create Issuer
  command: kubectl apply -f  /tmp/issuer.yaml -n kube-system
  become: yes
  become_user: root

- name: Copy Certificate
  template:
    src: certificate.yaml
    dest:  /tmp/certificate.yaml

- name: Check
  command: kubectl get certificate -n kube-system
  become: yes
  become_user: root
  register: certificate_check

- name: Delete Certificate
  command: kubectl delete certificate traefik-cert -n kube-system
  ignore_errors: True
  become: yes
  become_user: root
  when: "'traefik-cert' in certificate_check.stdout"

- name: Create Certificate
  command: kubectl apply -f  /tmp/certificate.yaml -n kube-system
  become: yes
  become_user: root
