- name: Copy Certificate 
  template: 
    src: certificate.yaml
    dest:  /tmp/certificate.yaml

- name: Delete Certificate 
  command: kubectl delete certificate traefik-cert -n kube-system
  ignore_errors: yes

- name: Create Certificate
  command: kubectl apply -f  /tmp/certificate.yaml -n kube-system

- name: Copy Issuer
  template: 
    src: issuer.yaml
    dest:  /tmp/issuer.yaml

- name: Delete Issuer 
  command: kubectl delete issuer letsencrypt-prod -n kube-system
  ignore_errors: yes

- name: Create Issuer
  command: kubectl apply -f  /tmp/issuer.yaml -n kube-system

- name: Configure RBAC
  command: kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml

- name: Copy traefik.tom
  copy: 
    src: templates/traefik.toml 
    dest: /tmp/traefik.toml

- command: kubectl delete configmap traefik-conf -n kube-system
  ignore_errors: yes

- name: Create configmap traefik-conf
  command: kubectl create configmap traefik-conf --from-file=/tmp/traefik.toml -n kube-system

- name: Copy Traefik DaemonSet
  copy: 
    src: templates/traefik-ds.yaml 
    dest: /tmp/traefik-ds.yaml

- name: Deploy traefik
  command: kubectl apply -f /tmp/traefik-ds.yaml -n kube-system