- name: Copy Issuer
  template:
    src: issuer.yaml
    dest:  /tmp/issuer.yaml

- name: Delete Issuer
  command: kubectl delete issuer letsencrypt-prod -n kube-system
  ignore_errors: yes

- name: Create Issuer
  command: kubectl apply -f  /tmp/issuer.yaml -n kube-system

- name: Copy Certificate
  template:
    src: certificate.yaml
    dest:  /tmp/certificate.yaml

- name: Delete Certificate
  command: kubectl delete certificate traefik-cert -n kube-system
  ignore_errors: yes

- name: Create Certificate
  command: kubectl apply -f  /tmp/certificate.yaml -n kube-system
  become: yes
  become_user: root

- name: Configure RBAC
  command: kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml
  become: yes
  become_user: root

- name: Copy traefik.tom
  copy:
    src: templates/traefik.toml
    dest: /tmp/traefik.toml

- name: "Delete Configmap traefik-conf"
  command: kubectl delete configmap traefik-conf -n kube-system
  ignore_errors: yes
  become: yes
  become_user: root

- name: Create configmap traefik-conf
  command: kubectl create configmap traefik-conf --from-file=/tmp/traefik.toml -n kube-system
  become: yes
  become_user: root

- name: Copy DaemonSet Traefik
  copy:
    src: templates/traefik-ds.yaml
    dest: /tmp/traefik-ds.yaml

- name: Delete DaemonSet traefik
  command: kubectl delete ds traefik-ingress-controller -n kube-system
  ignore_errors: yes
  become: yes
  become_user: root

- name: Deploy traefik
  command: kubectl apply -f /tmp/traefik-ds.yaml -n kube-system
  become: yes
  become_user: root
  