- name: Copy traefik.tom
  copy: src=templates/traefik.toml dest=/tmp/traefik.toml

- name: Copy Traefik DaemonSet
  copy: src=templates/traefik-ds-ssl.yaml dest=/tmp/traefik-ds.yaml

- name: Copy CRT
  copy: src=files/tls.crt dest=/tmp/tls.crt

- name: Copy KEY
  copy: src=files/tls.key dest=/tmp/tls.key

- name: Configure RBAC
  command: kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml

#- command: kubectl delete secret traefik-cert -n kube-system

- name: Create secret traefik-cert
  command: kubectl create secret generic traefik-cert --from-file=/tmp/tls.crt --from-file=/tmp/tls.key -n kube-system

#- command: kubectl delete configmap traefik-conf -n kube-system

- name: Create configmap traefik-conf
  command: kubectl create configmap traefik-conf --from-file=/tmp/traefik.toml -n kube-system

- name: Deploy traefik
  command: kubectl apply -f /tmp/traefik-ds.yaml