apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - grafana.{{domaine}}
    secretName: certificate
  rules:
  - host: grafana.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80