apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metrics-server
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - metrics-server.{{domaine}}
    secretName: certificate
  rules:
  - host: metrics-server.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: metrics-server
          servicePort: 443