---

- hosts: docker_nodes
  roles:
    - { role: docker_node }

- hosts: kubernetes_nodes
  roles:
    - { role: kubernetes_node }

- hosts: kubernetes_master_nodes
  roles:
    - { role: kubernetes_master_node }

- hosts: kubernetes_slave_nodes
  roles:
    - { role: kubernetes_slave_node }

- hosts: nfs_nodes
  roles:
    - { role: nfs_node }

- hosts: usine
  roles:
    - { role: usine }

- hosts: jenkins
  roles:
    - { role: jenkins }

- hosts: nexus
  roles:
    - { role: nexus }

- hosts: traefik
  roles:
    - { role: traefik }