- name: "Status folder {{ item.local }}"
  stat:
    path:  "{{ item.local }}"
  register: folder_status
  become: yes
  become_user: root

- name: "Create local Mount Folder"
  file:
    path: "{{ item.local }}"
    state: directory
  become: yes
  when: not (folder_status.stat.exists)

- name: "Unmount folder"
  mount:
    src: "{{ item.remote }}"
    path: "{{ item.local }}"
    state: unmounted
    fstype: nfs
  become: yes

- name: "Mount folder"
  mount:
    src: "{{ item.remote }}"
    path: "{{ item.local }}"
    state: mounted
    fstype: nfs
  become: yes
