- name: Create Folder /var/lib/kube-proxy
  file:
    path: /var/lib/kube-proxy
    state: directory
  become: yes
  become_user: root

- name: "Set kubernetes master group"
  set_fact:
    kubernetes_master_group: 'kubernetes-master'
  when: "'tag_Name_master' not in groups"

- name: "Set kubernetes master group"
  set_fact:
    kubernetes_master_group: 'tag_Name_master'
  when: "'tag_Name_master' in groups"

- debug:
    msg: "{{ hostvars[groups[kubernetes_master_group] }} "

- name: "Join cluster {{ hostvars[groups[kubernetes_master_group][0]]['join_master'] }}"
  command: "{{ hostvars[groups[kubernetes_master_group][0]]['join_master'] | replace('10.0.2.15', '10.0.0.2') }}"
  become: yes
  become_user: root
  when: kubeadm.init.options is defined

- name: "Join cluster {{ hostvars[groups[kubernetes_master_group][0]]['join_master'] }}"
  command: "{{ hostvars[groups[kubernetes_master_group][0]]['join_master'] }}"
  become: yes
  become_user: root
  when: kubeadm.init.options is not defined