- name: Reset Kubernetes
  command: kubeadm reset
  become: yes
  become_user: root

- name: "Join cluster {{ hostvars[groups['kubernetes-master'][0]]['join_master'] }}"
  command: "{{ hostvars[groups['kubernetes-master'][0]]['join_master'] }}"
  become: yes
  become_user: root