- name: Copy app Docker Service File
  template:
    src: service.j2
    dest: /etc/systemd/system/app.service
  become: true

- name: Daemon Reload app
  systemd:
    state: restarted
    daemon_reload: yes
    name: app

- name: Start app Service
  systemd:
    name: app
    state: started
    enabled: yes
  become: yes
  become_user: root