- name: Copy Resources
  template:
    src: "templates/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
  - ingress.yml

- name: Create Resources
  command: "kubectl apply -f /tmp/{{item}}"
  become: yes
  with_items:
  - ingress.yml

- name: Helm List
  command: helm list
  become: yes
  become_user: root
  register: helm_list

- name: Install metrics-server
  command: helm install --name metrics-server stable/metrics-server
  become: yes
  when: "'metrics-server' not in helm_list.stdout"