apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: octobercms
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
    - secretName: traefik-cert
  rules:
  - host: octobercms.{{domaine}}
    http:
      paths:
      - path: /
        backend:
          serviceName: octobercms
          servicePort: 80
